#Analytics Tracking
sg_ga: UA-19247091-8

# Styleguide settings
sg_title: Living Style Guide
sg_version: 1.0
sg_keywords: style guide, playbook, design, code 
sg_author: Matthew Elsom
sg_description: This Living Style Guide maintains design and code standards and documentation for a digital user interface.
sg_language: en
sg_styles: /styleguide/css/styleguide.css
sg_favicon: /styleguide/branding/favicon.ico
# Enable sass to edit Styleguide Template Styles
sass:
  sass_dir: styleguide/_scss #[generate Styleguide styles]
  style: :compressed

# Preprocessor settings
#highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# Jekyll Serve
port: 4000

# Output settings
title: STYLEGUIDE NAME
version: VERSION
keywords: KEYWORDS
author: AUTHOR NAME
description: DESCRIPTION
language: en
baseurl:
destination: _site
#sass:
#  sass_dir: src/assets/_scss #[generate Product styles]
#  style: :compressed

# Permalink
#permalink: /:categories/:title/

# Collections
collections:
  docs: 
    output: true
  patterns: 
    output: true  
    
defaults:
  - 
    scope:
      path: "_docs"
    values:
      layout: doc
      type: doc
  - 
    scope:
      path: "_docs/foundations"
    values:
      layout: doc
      type: foundations
  - 
    scope:
      path: "_docs/about"
    values:
      layout: doc
      type: about
  - 
    scope:
      path: "_docs/examples"
    values:
      layout: example
      type: example
  - 
    scope:
      path: "src/patterns"
    values:
      layout: pattern
      type: pattern
      maturity: planned
      title: Not Assigned
      styles: Not Assigned